# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70%
        threshold: 5%

# Ignore paths from coverage calculation
ignore:
  - "projects/angular-editor-app/"
  - "tmp/"

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false
